import Script from 'next/script'
import Head from 'next/head'
;<Head>
  <title>Miracle Dave Foundation</title>
  <meta name='description' content='Generated by create next app' />
  <link rel='icon' href='/favicon.ico' />{' '}
  <Script src='https://donorbox.org/widget.js' paypalExpress='false' />
</Head>

export default function donations() {
  const styles = {
    maxWidth: '500px',
    minWidth: '250px',
    maxHeight: 'none!important',
  }
  return (
    <>
      <div className='container mx-auto'>
        <iframe
          src='https://donorbox.org/embed/fund-a-child'
          name='donorbox'
          allowpaymentrequest='allowpaymentrequest'
          seamless='seamless'
          frameBorder='0'
          scrolling='no'
          height='900px'
          width='100%'
          style={styles}
        />
      </div>
    </>
  )
}
