// import Image from 'next/image'
import Head from 'next/head'
import Layout from '~/components/Layout'
import HeroComponent from '~/components/Hero'
import About from '~/components/About'
import OurMission from '~/components/OurMission'
import OurImpact from '~/components/OurImpact'

function Home() {
  return (
    <>
      <Head>
        <title>Miracle Dave Foundation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HeroComponent />

      <main className='container mx-auto'>
        {/* About  */}
        <About />
        {/* Our Mission */}
        <OurMission />
        {/* Our Impact */}

        <OurImpact />
      </main>
    </>
  )
}

export default Home
