// import Image from 'next/image'
import Head from 'next/head'
import Layout from '~/components/Layout'
import HeroComponent from '~/components/Hero'

function Home() {
  return (
    <div>
      <Head>
        <title>Miracle Dave Foundation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HeroComponent />
      <div>Layout</div>
    </div>
  )
}

export default Home
